#!/usr/bin/sage
# vim: syntax=python
# vim: set ts=2 sw=2 et:

# Standalone script to generate BN254 G2 4D decomposition lookup table
# This script contains all necessary functions inlined for standalone operation

import os

# Working directory
os.chdir(os.path.dirname(__file__))

from sage.structure.proof.all import arithmetic
arithmetic(False)

# Inlined curve constants for BN254_Snarks
def get_bn254_constants():
    """Get BN254 curve constants - inlined for standalone operation"""
    # BN254_Snarks parameters
    u = 0x44e992b44a6909f1
    p = 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47
    r = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001
    t = 0x6f4d8248eeb859fbf83e9682e87cfd47
    
    lambda_psi = (t - 1) % r
    lattice = derive_lattice(r, lambda_psi, 4)
    return r, lambda_psi, lattice

def derive_lattice(r, lambdaR, m):
    """Derive lattice matrix for scalar decomposition"""
    lat = Matrix(matrix.identity(m))
    lat[0, 0] = r
    for i in range(1, m):
        lat[i, 0] = -lambdaR**i
    return lat.LLL()

def decompose_scalar_g2_lattice(k, lattice):
    """Lattice-based scalar decomposition"""
    k_vec = vector([k, 0, 0, 0])
    alpha = k_vec * lattice.inverse()
    alpha_rounded = vector([round(a) for a in alpha])
    short_vec = k_vec - alpha_rounded * lattice
    return tuple(short_vec)

def precompute_power_of_2_decompositions():
    """Precompute 4D decompositions for all powers of 2"""
    r, lambda_psi, lattice = get_bn254_constants()
    
    # Determine how many bits we need (up to log2(r))
    max_bits = int(r).bit_length()
    
    precomputed_table = {}
    
    for i in range(max_bits):
        power_of_2 = 1 << i  # 2^i
        k0, k1, k2, k3 = decompose_scalar_g2_lattice(power_of_2, lattice)
        
        # Handle negative values by storing absolute value + sign flag
        decomp = []
        neg_flags = []
        
        for val in [k0, k1, k2, k3]:
            if val < 0:
                decomp.append(-val)
                neg_flags.append(True)
            else:
                decomp.append(val)
                neg_flags.append(False)
        
        precomputed_table[i] = {
            'power': power_of_2,
            'decomp': decomp,
            'neg_flags': neg_flags,
            'original': [k0, k1, k2, k3]
        }
    
    return precomputed_table, max_bits

def output_rust_table():
    """Output the precomputed table in exact Rust format requested"""
    precomputed_table, max_bits = precompute_power_of_2_decompositions()
    
    print("/// Precomputed 4D decompositions for powers of 2 (2^0 through 2^253)")
    print("/// Each entry contains (k0, k1, k2, k3, neg0, neg1, neg2, neg3)")
    print("/// Generated by bn254_table.sage")
    print(f"pub const POWER_OF_2_DECOMPOSITIONS: [(u128, u128, u128, u128, bool, bool, bool, bool); {max_bits}] = [")
    
    for i in range(max_bits):
        if i in precomputed_table:
            entry = precomputed_table[i]
            decomp = entry['decomp']
            neg_flags = entry['neg_flags']
            
            print(f"    // 2^{i}")
            print("    (")
            print(f"        0x{decomp[0]:032x},")
            print(f"        0x{decomp[1]:032x},")
            print(f"        0x{decomp[2]:032x},")
            print(f"        0x{decomp[3]:032x},")
            print(f"        {str(neg_flags[0]).lower()},")
            print(f"        {str(neg_flags[1]).lower()},")
            print(f"        {str(neg_flags[2]).lower()},")
            print(f"        {str(neg_flags[3]).lower()},")
            print("    ),")
    
    print("];")

# Main execution - only output the table
if __name__ == "__main__":
    output_rust_table()