#![allow(unused_imports)]
use ark_algebra_test_templates::*;
use ark_ec::{
    models::short_weierstrass::SWCurveConfig, // Keep this as G1 is SW
    pairing::Pairing,
    AffineRepr,
    CurveGroup,
    PrimeGroup,
};
use ark_ff::{
    biginteger::{BigInt, BigInteger, BigInteger256},
    fields::{FftField, Field, Fp6Config, PrimeField},
    One, UniformRand, Zero,
};
use ark_std::{
    cmp::Ordering,
    ops::{AddAssign, MulAssign},
    rand::Rng,
    test_rng,
};

// Add imports for the newly defined types
use crate::bn254::{
    CompressibleFq12, Fq, Fq12, Fq2, Fq6, FqConfig, Fr, FrConfig, G1Affine, G1Projective,
};

use ark_algebra_test_templates::*;

test_field!(fr; Fr; mont_prime_field);
// Uncomment Fq test
test_field!(fq; Fq; mont_prime_field);
test_field!(fq2; Fq2);
test_field!(fq6; Fq6);
test_field!(fq12; Fq12);

test_field!(compressible_fq12; CompressibleFq12);

// Uncomment G1 test for Short Weierstrass
test_group!(g1; G1Projective; sw);

// Add other tests for G2, Pairing etc. as needed
#[cfg(test)]
mod test {
    use ark_ff::{AdditiveGroup, Field, Fp12Config, Fp6Config, UniformRand};
    use ark_std::test_rng;

    use crate::bn254::{Fq12, Fq12Config, Fq2, Fq6, Fq6Config};

    #[test]
    fn test_compression() {
        // Fq12 is a quadratic extension of Fq6 whose Galois group is generated by the q6-Frobenius.
        let q6_minus_1: [u64; 24] = [
            0xf4e90a2716e3f810,
            0xbda8be6dec90ce20,
            0x725d28e938e58016,
            0xd65418b4cf130588,
            0xdd0e6a4e64b8148f,
            0x5408128686d835cb,
            0xa0903665952d6b92,
            0x6cc7afd0826c9a44,
            0xae01ee1f7c6ee657,
            0x8005dfa955bf9647,
            0x294d13656f6eb160,
            0x1e1342fb2628372f,
            0x28ec557b543fe50a,
            0x7e1c1d370decdf21,
            0x4661aaf35ddfdf5c,
            0xaebe67f05f148be1,
            0x64ed3d397a42c302,
            0x2ee8ac393e1f9708,
            0xea5ef61762dd07aa,
            0xd9df3dc41c5830ec,
            0x53500facde502233,
            0xf1f18061c3d30194,
            0x2a255aea70a6ec3a,
            0x2fd70ffd469f2,
        ];

        let psi_6: [u64; 32] = [
            0x72ab9d4cf9110b20,
            0x973cd2a37a1b4236,
            0x1ba98b1bc336a6d5,
            0x2dfcbbaca5d60846,
            0xd5439cc568e9448a,
            0xe1db0edd8549f5a5,
            0x6f93e1753d4af731,
            0x49c8a9c36c6fee88,
            0x15f3f80815d4b9fa,
            0x1ba650a506fe3ed0,
            0xaefe7d8fff4f3dff,
            0x6ac0657132447def,
            0xf1f3ac284dd0152c,
            0x37018c9976be9e50,
            0x22c60855715fb2d0,
            0x208847a342f135b0,
            0x3ee1e2cb94f42a1d,
            0x3c4a7ccbcfffdab3,
            0xad8c7c82ecaf3f33,
            0x6ca3fffc37db0759,
            0x37cd075497b1b668,
            0xea10af7b063fb6d2,
            0x4c05f030809f6505,
            0x2a2ce31f8f0d0104,
            0x8cabad13097c3c76,
            0x4d2a25ff065eb903,
            0xa3df56ffaff05a83,
            0x2d5b0867d19408a1,
            0x223eaadf9b381c71,
            0xe8809c2c51000097,
            0x0e97a02f2739dcf3,
            0x1b59e685800b,
        ];

        let q2: [u64; 8] = [
            0x3b5458a2275d69b1,
            0xa602072d09eac101,
            0x4a50189c6d96cadc,
            0x04689e957a1242c8,
            0x26edfa5c34c6b38d,
            0xb00b855116375606,
            0x599a6f7c0348d21c,
            0x925c4b8763cbf9c,
        ];

        let q2_plus_1: [u64; 8] = [
            0x3b5458a2275d69b2,
            0xa602072d09eac101,
            0x4a50189c6d96cadc,
            0x04689e957a1242c8,
            0x26edfa5c34c6b38d,
            0xb00b855116375606,
            0x599a6f7c0348d21c,
            0x925c4b8763cbf9c,
        ];

        let num_trials = 5;
        let mut rng = test_rng();

        for _ in 0..num_trials {
            let a = Fq12::rand(&mut rng);
            let compressed = a.torus_compress_base_order_minus_one_pow();
            let decompressed = Fq12::torus_decompress(compressed);
            assert_eq!(a.pow(psi_6), a.pow(q6_minus_1).pow(q2_plus_1));
        }

        for _ in 0..num_trials {
            let a = Fq12::rand(&mut rng);
            let b = Fq12::rand(&mut rng);
            for i in [a, b] {
                let compressed = i.torus_compress_base_order_minus_one_pow();
                let decompressed = Fq12::torus_decompress(compressed);
                assert_eq!(i.pow(q6_minus_1), decompressed);
            }

            let prod = a * b;
            let compressed_prod = Fq12::mul_torus_compressed_elements(
                a.torus_compress_base_order_minus_one_pow(),
                b.torus_compress_base_order_minus_one_pow(),
            );
            let decompressed = Fq12::torus_decompress(compressed_prod);
            assert_eq!(prod.pow(q6_minus_1), decompressed);
        }

        // for _ in 0..num_trials {
        //     let fq12_ele = Fq12::rand(&mut rng);
        //     let c1 = fq12_ele.torus_compress_base_order_minus_one_pow();
        //     let c1_pow = c1.pow(q2);
        //     let compressed_prod = Fq12::mul_torus_compressed_elements(c1_pow, c1);
        //     assert_eq!(
        //         Fq12::torus_decompress(compressed_prod),
        //         Fq12::torus_decompress(c1).pow(q2_plus_1)
        //     );

        //     assert_eq!(
        //         Fq12::torus_decompress(c1).pow(q2_plus_1),
        //         fq12_ele.pow(psi_6)
        //     );

        //     // let compressed = TorusCompressedFq12::compress_to_fq6(fq12_ele);
        //     // let decompressed = Fq12::torus_decompress(compressed);
        //     // assert_eq!(fq12_ele.pow(psi_6), decompressed);
        // }
    }
}
